# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\study\nis3364\NIS3364-tyuChatRoom\client\login\login_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(1327, 629)
        self.label = QtWidgets.QLabel(LoginWindow)
        self.label.setGeometry(QtCore.QRect(1, 1, 831, 631))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/background/image/fuhua.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.LoginContainer = QtWidgets.QWidget(LoginWindow)
        self.LoginContainer.setEnabled(True)
        self.LoginContainer.setGeometry(QtCore.QRect(880, 210, 421, 381))
        self.LoginContainer.setObjectName("LoginContainer")
        self.LoginButton = PrimaryPushButton(self.LoginContainer)
        self.LoginButton.setGeometry(QtCore.QRect(20, 280, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.LoginButton.setFont(font)
        self.LoginButton.setObjectName("LoginButton")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.LoginContainer)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(19, 110, 361, 61))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setVerticalSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.UsernameLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.UsernameLabel.setFont(font)
        self.UsernameLabel.setObjectName("UsernameLabel")
        self.gridLayout_2.addWidget(self.UsernameLabel, 0, 0, 1, 1)
        self.UsernameEdit = LineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UsernameEdit.sizePolicy().hasHeightForWidth())
        self.UsernameEdit.setSizePolicy(sizePolicy)
        self.UsernameEdit.setClearButtonEnabled(True)
        self.UsernameEdit.setObjectName("UsernameEdit")
        self.gridLayout_2.addWidget(self.UsernameEdit, 1, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.LoginContainer)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 190, 361, 61))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setVerticalSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.PasswordLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PasswordLabel.setFont(font)
        self.PasswordLabel.setObjectName("PasswordLabel")
        self.gridLayout_3.addWidget(self.PasswordLabel, 0, 0, 1, 1)
        self.PasswordEdit = PasswordLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PasswordEdit.sizePolicy().hasHeightForWidth())
        self.PasswordEdit.setSizePolicy(sizePolicy)
        self.PasswordEdit.setObjectName("PasswordEdit")
        self.gridLayout_3.addWidget(self.PasswordEdit, 1, 0, 1, 1)
        self.RegisterButton = HyperlinkButton(self.LoginContainer)
        self.RegisterButton.setGeometry(QtCore.QRect(156, 340, 91, 31))
        self.RegisterButton.setObjectName("RegisterButton")
        self.LogoImage = QtWidgets.QLabel(LoginWindow)
        self.LogoImage.setGeometry(QtCore.QRect(970, 120, 201, 151))
        self.LogoImage.setText("")
        self.LogoImage.setPixmap(QtGui.QPixmap(":/background/image/logo.png"))
        self.LogoImage.setScaledContents(True)
        self.LogoImage.setObjectName("LogoImage")

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Form"))
        self.LoginButton.setText(_translate("LoginWindow", "登录"))
        self.UsernameLabel.setText(_translate("LoginWindow", "用户名"))
        self.PasswordLabel.setText(_translate("LoginWindow", "密码"))
        self.RegisterButton.setText(_translate("LoginWindow", "注册账号"))
from qfluentwidgets import HyperlinkButton, LineEdit, PasswordLineEdit, PrimaryPushButton
import resource_rc
