# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\study\nis3364\NIS3364-tyuChatRoom\client\ChatRoom\ChatRoom.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt


class Ui_ChatRoom_Window(object):
    def setupUi(self, ChatRoom_Window):
        ChatRoom_Window.setObjectName("ChatRoom_Window")
        ChatRoom_Window.resize(1155, 858)
        self.layoutWidget = QtWidgets.QWidget(ChatRoom_Window)
        self.layoutWidget.setGeometry(QtCore.QRect(-1, -1, 1091, 861))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(10, 0, 5, 10)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(-10, 0, 311, 861))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.layoutWidget1)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("QFrame#frame{\n"
"    border: 1px solid #d3d3d3;  /* 设置边框 */\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 281, 81))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.frame)
        self.UserListWidget = ListWidget(self.layoutWidget1)
        self.UserListWidget.setObjectName("UserListWidget")
        self.verticalLayout.addWidget(self.UserListWidget)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 16)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(300, 0, 786, 850))
        self.frame_3.setStyleSheet("QFrame #frame_3{\n"
"    background-color: #F3FCF9;  /* 设置背景颜色 */\n"
"    border: 1px solid #d3d3d3;  /* 设置边框 */\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.layoutWidget2 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(-1, 0, 781, 851))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.MessageScrollArea = SingleDirectionScrollArea(orient=Qt.Vertical)
        self.MessageScrollArea.setWidgetResizable(True)
        self.MessageScrollArea.setObjectName("MessageScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 777, 600))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.MessageScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.MessageScrollArea)
        self.frame_4 = QtWidgets.QFrame(self.layoutWidget2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.SendMessageButton = PrimaryPushButton(self.frame_4)
        self.SendMessageButton.setGeometry(QtCore.QRect(670, 190, 81, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendMessageButton.sizePolicy().hasHeightForWidth())
        self.SendMessageButton.setSizePolicy(sizePolicy)
        self.SendMessageButton.setObjectName("SendMessageButton")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(-1, -1, 781, 41))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_5)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 181, 31))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.EmojiButton = TransparentToolButton(self.layoutWidget_2)
        self.EmojiButton.setObjectName("EmojiButton")
        self.horizontalLayout_2.addWidget(self.EmojiButton)
        self.PhotoButton = TransparentToolButton(self.layoutWidget_2)
        self.PhotoButton.setObjectName("PhotoButton")
        self.horizontalLayout_2.addWidget(self.PhotoButton)
        self.FileButton = TransparentToolButton(self.layoutWidget_2)
        self.FileButton.setObjectName("FileButton")
        self.horizontalLayout_2.addWidget(self.FileButton)
        self.MessageEdit = PlainTextEdit(self.frame_4)
        self.MessageEdit.setGeometry(QtCore.QRect(3, 36, 781, 151))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.MessageEdit.setFont(font)
        self.MessageEdit.setStyleSheet("PlainTextEdit {\n"
"    background: transparent;\n"
"}")
        self.MessageEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.MessageEdit.setBackgroundVisible(False)
        self.MessageEdit.setObjectName("MessageEdit")
        self.frame_5.raise_()
        self.SendMessageButton.raise_()
        self.MessageEdit.raise_()
        self.verticalLayout_2.addWidget(self.frame_4)
        self.verticalLayout_2.setStretch(0, 15)
        self.verticalLayout_2.setStretch(1, 6)
        self.horizontalLayout.addWidget(self.frame_2)
        self.horizontalLayout.setStretch(0, 3)

        self.retranslateUi(ChatRoom_Window)
        QtCore.QMetaObject.connectSlotsByName(ChatRoom_Window)

    def retranslateUi(self, ChatRoom_Window):
        _translate = QtCore.QCoreApplication.translate
        ChatRoom_Window.setWindowTitle(_translate("ChatRoom_Window", "Form"))
        self.label.setText(_translate("ChatRoom_Window", "在线用户"))
        self.SendMessageButton.setText(_translate("ChatRoom_Window", "发送"))
        self.EmojiButton.setText(_translate("ChatRoom_Window", "..."))
        self.PhotoButton.setText(_translate("ChatRoom_Window", "..."))
        self.FileButton.setText(_translate("ChatRoom_Window", "..."))
from qfluentwidgets import ListWidget, PlainTextEdit, PrimaryPushButton, SingleDirectionScrollArea, TransparentToolButton
import resource_rc
