# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\study\nis3364\NIS3364-tyuChatRoom\client\ChatRoom\ChatRoom.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChatRoom_Window(object):
    def setupUi(self, ChatRoom_Window):
        ChatRoom_Window.setObjectName("ChatRoom_Window")
        ChatRoom_Window.resize(1100, 859)
        self.widget = QtWidgets.QWidget(ChatRoom_Window)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 1101, 861))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(10, 0, 10, 10)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setGeometry(QtCore.QRect(-10, 0, 311, 61))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("QFrame#frame{\n"
"    border: 1px solid #d3d3d3;  /* 设置边框 */\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 10, 229, 39))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.widget)
        self.frame_3.setStyleSheet("QFrame #frame_3{\n"
"    background-color: #F3FCF9;  /* 设置背景颜色 */\n"
"    border: 1px solid #d3d3d3;  /* 设置边框 */\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setGeometry(QtCore.QRect(-1, 609, 791, 231))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.SendMessageButton = PrimaryPushButton(self.frame_4)
        self.SendMessageButton.setGeometry(QtCore.QRect(670, 190, 81, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendMessageButton.sizePolicy().hasHeightForWidth())
        self.SendMessageButton.setSizePolicy(sizePolicy)
        self.SendMessageButton.setObjectName("SendMessageButton")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(-1, -1, 791, 41))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.MessageEdit = PlainTextEdit(self.frame_4)
        self.MessageEdit.setGeometry(QtCore.QRect(3, 36, 781, 151))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.MessageEdit.setFont(font)
        self.MessageEdit.setStyleSheet("PlainTextEdit {\n"
"    background: transparent;\n"
"}")
        self.MessageEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.MessageEdit.setBackgroundVisible(False)
        self.MessageEdit.setObjectName("MessageEdit")
        self.line = QtWidgets.QFrame(self.frame_3)
        self.line.setGeometry(QtCore.QRect(-3, 600, 791, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.widget1 = QtWidgets.QWidget(self.frame_3)
        self.widget1.setGeometry(QtCore.QRect(10, 610, 161, 41))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.EmojiButton = TransparentToolButton(self.widget1)
        self.EmojiButton.setObjectName("EmojiButton")
        self.horizontalLayout_2.addWidget(self.EmojiButton)
        self.PhotoButton = TransparentToolButton(self.widget1)
        self.PhotoButton.setObjectName("PhotoButton")
        self.horizontalLayout_2.addWidget(self.PhotoButton)
        self.FileButton = TransparentToolButton(self.widget1)
        self.FileButton.setObjectName("FileButton")
        self.horizontalLayout_2.addWidget(self.FileButton)
        self.horizontalLayout.addWidget(self.frame_3)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 8)

        self.retranslateUi(ChatRoom_Window)
        QtCore.QMetaObject.connectSlotsByName(ChatRoom_Window)

    def retranslateUi(self, ChatRoom_Window):
        _translate = QtCore.QCoreApplication.translate
        ChatRoom_Window.setWindowTitle(_translate("ChatRoom_Window", "Form"))
        self.label.setText(_translate("ChatRoom_Window", "在线用户"))
        self.SendMessageButton.setText(_translate("ChatRoom_Window", "发送"))
        self.EmojiButton.setText(_translate("ChatRoom_Window", "..."))
        self.PhotoButton.setText(_translate("ChatRoom_Window", "..."))
        self.FileButton.setText(_translate("ChatRoom_Window", "..."))
from qfluentwidgets import PlainTextEdit, PrimaryPushButton, TransparentToolButton
import resource_rc
